use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
# config :kekbot, KekbotWeb.Endpoint,
#   url: [scheme: "https", host: "kekbot-7133.nodechef.com", port: 443],
#   force_ssl: [rewrite_on: [:x_forwarded_proto]],
#   secret_key_base: Map.fetch!(System.get_env(), "SECRET_KEY_BASE")

# Do not print debug messages in production

config :kekbot, Kekbot.Endpoint,
  load_from_system_env: true,
  url: [host: "${APP_NAME}.gigalixirapp.com", port: 80],

config :kekbot, Kekbot.Endpoint,
  server: true,
  secret_key_base: "${SECRET_KEY_BASE}"

# Do not print debug messages in production
config :logger, level: :info

config :kekbot, Kekbot.Repo,
  adapter: Ecto.Adapters.Postgres,
  url: "${DATABASE_URL}",
  database: "",
  ssl: true,
  pool_size: 1

config :libcluster,
  topologies: [
    k8s_example: [
      strategy: Cluster.Strategy.Kubernetes,
      config: [
        kubernetes_selector: "${LIBCLUSTER_KUBERNETES_SELECTOR}",
        kubernetes_node_basename: "${LIBCLUSTER_KUBERNETES_NODE_BASENAME}"]]]
